# =========================================================
# laboheme-blog 사이트 기본 정보
# =========================================================
title: "La Bohème Blog"               # 블로그 상단에 노출될 블로그 이름
email: "la.boheme.host@gmail.com"      # 본인 이메일 주소
description: >-                      # 검색엔진(구글 등)에 노출될 블로그 소개글
  티스토리에서 이전한 깃허브 블로그입니다.


# =========================================================
# GitHub Pages URL 및 스킨 CSS 경로 설정 (핵심 수정 부분)
# =========================================================
url: "https://la-boheme-host.github.io"   # 본인의 GitHub Pages 메인 도메인
baseurl: "/la-boheme"                     # Repository 이름을 하위 경로로 입력 (앞에 / 필수)

# =========================================================
# 티스토리 숫자 URL 보존 설정
# =========================================================
permalink: /:title/

# =========================================================
# 구글 애드센스 연동 설정
# =========================================================
google_adsense:
  enable: true
  client_id: "pub-8868289380135841" # 본인의 구글 애드센스 게시자 ID

# =========================================================
# 빌드 및 플러그인 설정
# =========================================================
theme: minima                        # 기본 디자인 테마
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 빌드 시 결과물에서 제외할 폴더 및 파일 목록
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor